### ISSUE TITLE
can't find jar file

### ISSUE THREAD

**Issue by cquezpro** [RemcoB00/cordova-phonegap_youtube_player_api_android#7]
plugin.xml says this,
 <source-file src="src/android/YouTubeAndroidPlayerApi.jar" target-dir="libs" />

but I can't find jar file on android folder.
did you remove?

**Comment by RemcoB00** [comment]
You can automatically install the plugin by running the `npm install remcob00-cordova-youtube-android-player-api` command (this command does also download the JAR file) or you can manual download the JAR file from [the Google Developers website](https://developers.google.com/youtube/android/player/downloads/).

I didn't include the JAR file in this GitHub repository since this file is owned by Google (YouTube) and I don't have the rights to upload it to GitHub.

**Comment by RemcoB00** [comment]
You can find the full installation instructions for the plugin [here](https://github.com/RemcoB00/cordova-phonegap_youtube_player_api_android/blob/master/README.md#installation).
